version: '3.7'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: ruzhyrskyi/lab4-examples:compose-django
    container_name: django
    ports:
      - 8000:8000
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.mon
    image: ruzhyrskyi/lab4-examples:compose-monitoring
    container_name: monitoring 
    network_mode: "host"
